### ISSUE TITLE
Vsync Off Option

### ISSUE THREAD

**Issue by shinra358** [Gemini-Loboto3/RE2-Mod-SDK#2]
We need this for ai frame generation to work properly (for all of the projects)

**Comment by Gemini-Loboto3** [comment]
There is no vsync.

**Comment by shinra358** [comment]
If there is no vsync option, the game adapts the vsync of the desktop. vsync needs to be turned off in order to use ai frame gen properly. So an option to disable vsync would be nice. The gog version even has this option but since this mod disables all of the gog enhancements, this is why I'm asking.

**Comment by Gemini-Loboto3** [comment]
Again, there is no vsync whatsoever. All frame pacing is done via timers.
