### ISSUE TITLE
AfterPluggin Controller Enhancement

### ISSUE THREAD

**Issue by shinra358** [Gemini-Loboto3/RE2-Mod-SDK#6]
After Plugging, the ability to turn on the controller after the game has already started and the controller still work.

Hot Plugging, the ability to disconnect and reconnect the controller midgame and have the controller still work.

This mod has Hot Plugging but not After Plugging. This is a necessary requirement for games. Currently, if you forget to turn the controller on before the game starts, you will have to exit the game and turn your controller on first to be able to play. Most modern emulators and all consoles have this feature as well as all modern pc games.

**Comment by Gemini-Loboto3** [comment]
This is dedicated to SDK discussions, stop asking here for features for the patch.
