### ISSUE TITLE
Anisotropic Filtering and MSAA enhancements

### ISSUE THREAD

**Issue by shinra358** [Gemini-Loboto3/RE2-Mod-SDK#7]
Just like the gog version, would like these graphical enhancements for this mod for dgvd2 versions have lines in the sprites while gog's versions dont. dgvd2 msaa also slows down the game while gog's msaa doesnt. So i would like optimized versions of these options.

**Comment by Gemini-Loboto3** [comment]
Then you should ask dege, dgvoodoo's author, not me. I have nothing to do with those wrappers, also this is the SDK section, not a request section for the main patch.
